# Generated by Django 2.1.7 on 2019-07-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scripts', models.CharField(max_length=20)),
                ('json_file', models.FileField(upload_to='jsonfiles')),
            ],
        ),
    ]
